model_path:
  pretrained_model_name_or_path: ./pretrained_models/StableDiffusion
  clip_vision_encoder_path: ./pretrained_models/models/clip-vit-large-patch14
  controlnet_model_name: './pretrained_models/models/control_v11p_sd15_lineart'
  annotator_ckpts_path: ./pretrained_models/models/Annotators
  manga_control_model_path: ./pretrained_models/MangaNinjia/controlnet.pth
  manga_reference_model_path: ./pretrained_models/MangaNinjia/reference_unet.pth
  manga_main_model_path: ./pretrained_models/MangaNinjia/denoising_unet.pth
  point_net_path: ./pretrained_models/MangaNinjia/point_net.pth
inference_config:
  output_path: output
  device: cuda